name: Build

on:
  workflow_dispatch:
    inputs:
      build_variant:
        description: 'Build variant to test'
        default: 'treble_arm64_bgN'
        required: false
        type: string
  push:
    branches:
      - android-14.0
    paths-ignore:
      - '.github/**'
      - 'config/**'

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Build Variant
        run: echo "BUILD_VARIANT=${{ inputs.build_variant || 'treble_arm64_bgN' }}" >> $GITHUB_ENV

      - name: Setup Env
        run: sudo apt-get install repo python3
        
      - name: Build ROM
        run: bash build.sh

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_VARIANT }}
          path: builds/*.xz
