name: Build

on:
  workflow_dispatch:
    inputs:
      build_variant:
        description: 'Build variant to test'
        default: 'treble_arm64_bgN'
        required: false
        type: string
  push:
    branches:
      - android-14.0
    paths-ignore:
      - '.github/**'
      - 'config/**'

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Build Variant
        run: echo "BUILD_VARIANT=${{ inputs.build_variant || 'treble_arm64_bgN' }}" >> $GITHUB_ENV

      - name: Setup Env
        run: sudo apt-get install repo python3 bc bison build-essential curl flex g++-multilib gcc-multilib git gnupg gperf libxml2 \
lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev imagemagick git \
lunzip lzop schedtool squashfs-tools xsltproc zip zlib1g-dev openjdk-8-jdk python perl  \
xmlstarlet virtualenv xz-utils rr jq libncurses5 pngcrush lib32ncurses5-dev git-lfs libxml2 \
openjdk-11-jdk-headless && git lfs install 
        
      - name: Build ROM
        run: bash build.sh

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_VARIANT }}
          path: builds/*.xz
